```yaml
name: Terraform Exercise 4

on:
  push:
    branches:
      - main
    paths:
      - 'exercise4/**'

  pull_request:
    branches:
      - main
    paths:
      - 'exercise4/**'

jobs:
  terraform:
    name: Terraform Exercise 4
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./exercise4

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 3. Check AWS l
```
