name: Terraform Exercise 4

on:
  push:
    branches:
      - main
    paths:
      - 'exercise4/**'

  pull_request:
    branches:
      - main
    paths:
      - 'exercise4/**'

jobs:
  terraform:
    name: Terraform Exercise 4
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./exercise4

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 3. Check AWS login
      - name: Check AWS Login
        run: |
          aws sts get-caller-identity

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

